[manager]

keymap = [
	{ on = [ "<Esc>" ], exec = "escape" },
	{ on = [ "q" ], exec = "quit" },
	{ on = [ "<C-q>" ], exec = "close" },
	{ on = [ "<C-z>" ], exec = '''shell "$SHELL" --block --confirm''' },

	# Navigation
	{ on = [ "u" ], exec = "arrow -1" },
	{ on = [ "e" ], exec = "arrow 1" },

	{ on = [ "U" ], exec = "arrow -5" },
	{ on = [ "E" ], exec = "arrow 5" },

	{ on = [ "n" ], exec = [ "leave", "escape --visual --select" ] },
	{ on = [ "i" ], exec = [ "plugin --sync enter-or-open", "escape --visual --select" ] },

	{ on = [ "N" ], exec = "back" },
	{ on = [ "I" ], exec = "forward" },

	{ on = [ "<C-u>" ], exec = "seek -5" },
	{ on = [ "<C-e>" ], exec = "seek 5" },

	{ on = [ "g", "g" ], exec = "arrow -99999999" },
	{ on = [ "G" ],      exec = "arrow 99999999" },

	# Selection
	{ on = [ "<Space>" ], exec = [ "select --state=none", "arrow 1" ] },
	{ on = [ "v" ], exec = "visual_mode" },
	{ on = [ "V" ], exec = "visual_mode --unset" },
	{ on = [ "<C-a>" ], exec = "select_all --state=true" },
	{ on = [ "<C-r>" ], exec = "select_all --state=none" },

	# Operation
	{ on = [ "<Enter>" ], exec = "open" },
	{ on = [ "<C-Enter>" ], exec = "open --interactive" },
	{ on = [ "y" ], exec = [ "yank", "escape --visual --select" ] },
	{ on = [ "x" ], exec = [ "yank --cut", "escape --visual --select" ] },
	{ on = [ "p" ], exec = "paste" },
	{ on = [ "P" ], exec = "paste --force" },
	{ on = [ "l" ], exec = "link" },
	{ on = [ "L" ], exec = "link --relative" },
	{ on = [ "d" ], exec = [ "remove", "escape --visual --select" ] },
	{ on = [ "D" ], exec = [ "remove --permanently", "escape --visual --select" ] },
	{ on = [ "a" ], exec = "create" },
	{ on = [ "r" ], exec = "rename --cursor=before_ext" },
	{ on = [ ";" ], exec = "shell" },
	{ on = [ ":" ], exec = "shell --block" },
	{ on = [ "h" ], exec = "hidden toggle" },
	{ on = [ "s" ], exec = "search fd" },
	{ on = [ "S" ], exec = "search rg" },
	{ on = [ "<C-s>" ], exec = "search none" },
	{ on = [ "z" ], exec = "jump zoxide" },
	{ on = [ "Z" ], exec = "jump fzf" },

	# Linemode
	{ on = [ "m", "s" ], exec = "linemode size" },
	{ on = [ "m", "p" ], exec = "linemode permissions" },
	{ on = [ "m", "m" ], exec = "linemode mtime" },
	{ on = [ "m", "n" ], exec = "linemode none" },

	# Copy
	{ on = [ "c", "c" ], exec = "copy path" },
	{ on = [ "c", "d" ], exec = "copy dirname" },
	{ on = [ "c", "f" ], exec = "copy filename" },
	{ on = [ "c", "n" ], exec = "copy name_without_ext" },

	# Filter
	{ on = [ "f" ], exec = "filter" },

	# Find
	{ on = [ "/" ], exec = "find --smart" },
	{ on = [ "?" ], exec = "find --previous --smart" },
	{ on = [ "-" ], exec = "find_arrow" },
	{ on = [ "=" ], exec = "find_arrow --previous" },

	# Sorting
	{ on = [ ",", "m" ], exec = "sort modified --dir-first",               desc = "Sort by modified time" },
	{ on = [ ",", "M" ], exec = "sort modified --reverse --dir-first",     desc = "Sort by modified time (reverse)" },
	{ on = [ ",", "c" ], exec = "sort created --dir-first",                desc = "Sort by created time" },
	{ on = [ ",", "C" ], exec = "sort created --reverse --dir-first",      desc = "Sort by created time (reverse)" },
	{ on = [ ",", "e" ], exec = "sort extension --dir-first",         	   desc = "Sort by extension" },
	{ on = [ ",", "E" ], exec = "sort extension --reverse --dir-first",    desc = "Sort by extension (reverse)" },
	{ on = [ ",", "a" ], exec = "sort alphabetical --dir-first",           desc = "Sort alphabetically" },
	{ on = [ ",", "A" ], exec = "sort alphabetical --reverse --dir-first", desc = "Sort alphabetically (reverse)" },
	{ on = [ ",", "n" ], exec = "sort natural --dir-first",                desc = "Sort naturally" },
	{ on = [ ",", "N" ], exec = "sort natural --reverse --dir-first",      desc = "Sort naturally (reverse)" },
	{ on = [ ",", "s" ], exec = "sort size --dir-first",                   desc = "Sort by size" },
	{ on = [ ",", "S" ], exec = "sort size --reverse --dir-first",         desc = "Sort by size (reverse)" },

	# Tabs
	{ on = [ "t" ], exec = "tab_create --current" },

	{ on = [ "<C-n>" ], exec = "tab_switch -1 --relative" },
	{ on = [ "<C-i>" ], exec = "tab_switch 1 --relative" },

	{ on = [ "1" ], exec = "tab_switch 0" },
	{ on = [ "2" ], exec = "tab_switch 1" },
	{ on = [ "3" ], exec = "tab_switch 2" },
	{ on = [ "4" ], exec = "tab_switch 3" },
	{ on = [ "5" ], exec = "tab_switch 4" },
	{ on = [ "6" ], exec = "tab_switch 5" },
	{ on = [ "7" ], exec = "tab_switch 6" },
	{ on = [ "8" ], exec = "tab_switch 7" },
	{ on = [ "9" ], exec = "tab_switch 8" },

	{ on = [ "<" ], exec = "tab_swap -1" },
	{ on = [ ">" ], exec = "tab_swap 1" },

	# Tasks
	{ on = [ "w" ], exec = "tasks_show" },

	# Goto
	{ on = [ "g", "h" ], exec = "cd ~" },
	{ on = [ "g", "c" ], exec = "cd ~/.config" },
	{ on = [ "g", "d" ], exec = "cd ~/Downloads" },
	{ on = [ "g", "t" ], exec = "cd /tmp" },
	{ on = [ "g", "o" ], exec = "cd ~/Library/CloudStorage/OneDrive-SQUAREENIX" },
	{ on = [ "g", "<Space>" ], exec = "cd --interactive" },

	# Help
	{ on = [ "~" ], exec = "help" },
]

[tasks]

keymap = [
	{ on = [ "<C-q>" ], exec = "close" },
	{ on = [ "<Esc>" ], exec = "close" },
	{ on = [ "w" ], exec = "close" },

	{ on = [ "u" ], exec = "arrow -1" },
	{ on = [ "e" ], exec = "arrow 1" },

	{ on = [ "<Enter>" ], exec = "inspect" },
	{ on = [ "x" ], exec = "cancel" },

	{ on = [ "~" ], exec = "help" },
]

[select]

keymap = [
	{ on = [ "<C-q>" ], exec = "close" },
	{ on = [ "<Esc>" ], exec = "close" },
	{ on = [ "<Enter>" ], exec = "close --submit" },

	{ on = [ "u" ], exec = "arrow -1" },
	{ on = [ "e" ], exec = "arrow 1" },

	{ on = [ "U" ], exec = "arrow -5" },
	{ on = [ "E" ], exec = "arrow 5" },

	{ on = [ "~" ], exec = "help" },
]

[input]

keymap = [
	{ on = [ "<C-q>" ],   exec = "close",          desc = "Cancel input" },
	{ on = [ "<Enter>" ], exec = "close --submit", desc = "Submit the input" },
	{ on = [ "<Esc>" ],   exec = "escape",         desc = "Go back the normal mode, or cancel input" },

	# Mode
	{ on = [ "k" ], exec = "insert",                              desc = "Enter insert mode" },
	{ on = [ "a" ], exec = "insert --append",                     desc = "Enter append mode" },
	{ on = [ "<C-n>" ], exec = [ "move -999", "insert" ],         desc = "Move to the BOL, and enter insert mode" },
	{ on = [ "<C-i>" ], exec = [ "move 999", "insert --append" ], desc = "Move to the EOL, and enter append mode" },
	{ on = [ "v" ], exec = "visual",                              desc = "Enter visual mode" },
	{ on = [ "V" ], exec = [ "move -999", "visual", "move 999" ], desc = "Enter visual mode and select all" },

	# Character-wise movement
	{ on = [ "n" ],       exec = "move -1", desc = "Move back a character" },
	{ on = [ "i" ],       exec = "move 1",  desc = "Move forward a character" },
	{ on = [ "<Left>" ],  exec = "move -1", desc = "Move back a character" },
	{ on = [ "<Right>" ], exec = "move 1",  desc = "Move forward a character" },
	{ on = [ "<C-b>" ],   exec = "move -1", desc = "Move back a character" },
	{ on = [ "<C-f>" ],   exec = "move 1",  desc = "Move forward a character" },

	# Word-wise movement
	{ on = [ "b" ],     exec = "backward",              desc = "Move back to the start of the current or previous word" },
	{ on = [ "w" ],     exec = "forward",               desc = "Move forward to the start of the next word" },
	{ on = [ "h" ],     exec = "forward --end-of-word", desc = "Move forward to the end of the current or next word" },
	{ on = [ "<A-b>" ], exec = "backward",              desc = "Move back to the start of the current or previous word" },
	{ on = [ "<A-f>" ], exec = "forward --end-of-word", desc = "Move forward to the end of the current or next word" },

	# Line-wise movement
	{ on = [ "N" ],     exec = "move -999", desc = "Move to the BOL" },
	{ on = [ "I" ],     exec = "move 999",  desc = "Move to the EOL" },
	{ on = [ "<C-a>" ], exec = "move -999", desc = "Move to the BOL" },
	{ on = [ "<C-e>" ], exec = "move 999",  desc = "Move to the EOL" },

	# Delete
	{ on = [ "<Backspace>" ], exec = "backspace",	        desc = "Delete the character before the cursor" },
	{ on = [ "<C-h>" ],       exec = "backspace",         desc = "Delete the character before the cursor" },
	{ on = [ "<C-d>" ],       exec = "backspace --under", desc = "Delete the character under the cursor" },

	# Kill
	{ on = [ "<C-u>" ], exec = "kill bol",      desc = "Kill backwards to the BOL" },
	{ on = [ "<C-k>" ], exec = "kill eol",      desc = "Kill forwards to the EOL" },
	{ on = [ "<C-w>" ], exec = "kill backward", desc = "Kill backwards to the start of the current word" },
	{ on = [ "<A-d>" ], exec = "kill forward",  desc = "Kill forwards to the end of the current word" },

	# Cut/Yank/Paste
	{ on = [ "d" ], exec = "delete --cut",                              desc = "Cut the selected characters" },
	{ on = [ "D" ], exec = [ "delete --cut", "move 999" ],              desc = "Cut until the EOL" },
	{ on = [ "c" ], exec = "delete --cut --insert",                     desc = "Cut the selected characters, and enter insert mode" },
	{ on = [ "C" ], exec = [ "delete --cut --insert", "move 999" ],     desc = "Cut until the EOL, and enter insert mode" },
	{ on = [ "x" ], exec = [ "delete", "move 1 --in-operating" ],       desc = "Cut the current character" },
	{ on = [ "y" ], exec = "yank",           desc = "Copy the selected characters" },
	{ on = [ "p" ], exec = "paste",          desc = "Paste the copied characters after the cursor" },
	{ on = [ "P" ], exec = "paste --before", desc = "Paste the copied characters before the cursor" },

	# Undo/Redo
	{ on = [ "l" ],     exec = "undo", desc = "Undo the last operation" },
	{ on = [ "L" ], exec = "redo", desc = "Redo the last operation" },

	# Help
	{ on = [ "~" ], exec = "help", desc = "Open help" }
]

[help]

keymap = [
	{ on = [ "<Esc>" ], exec = "escape" },
	{ on = [ "q" ],     exec = "close" },
	{ on = [ "<C-q>" ], exec = "close" },

	# Navigation
	{ on = [ "u" ], exec = "arrow -1" },
	{ on = [ "e" ], exec = "arrow 1" },

	{ on = [ "U" ], exec = "arrow -5" },
	{ on = [ "E" ], exec = "arrow 5" },

	# Filtering
	{ on = [ "/" ], exec = "filter" },
]

[completion]

keymap = [
	{ on = [ "<C-q>" ], exec = "close" },
	{ on = [ "<Tab>" ], exec = "close --submit" },

	{ on = [ "<C-u>" ], exec = "arrow -1" },
	{ on = [ "<C-e>" ], exec = "arrow 1" },

	{ on = [ "~" ], exec = "help" }
]
