[mode]
normal   = { fg = "#1E2031", bg = "#80AEFA" }
select   = { fg = "#23273B", bg = "#CD9EFC" }
unselect = { fg = "#23273B", bg = "#FFA577" }

[tab]
active   = { fg = "", bg = "" }
inactive = { fg = "", bg = "" }

[selection]
normal   = { fg = "", bg = "" }
hovered  = { fg = "", bg = "" }
selected = { fg = "", bg = "" }

[filetype]

[syntect]
theme = "~/.config/bat/themes/Catppuccin-macchiato.tmTheme"

[icons]

"Desktop/"   = ""
"Documents/" = ""
"Downloads/" = ""
"Music/"     = ""
"Pictures/"  = ""
"Public/"    = ""
"Videos/"    = ""
".config/"   = ""

# Git
".git/"          = ""
".gitignore"     = ""
".gitmodules"    = ""
".gitattributes" = ""

# Dotfiles
".DS_Store"    = ""
".bashrc"      = ""
".bashprofile" = ""
".zshrc"       = ""
".zshenv"      = ""
".zprofile"    = ""
".vimrc"       = ""

# Text
"*.txt" = ""
"*.md"  = ""

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz"  = ""
"*.7z"  = ""

# Audio
"*.mp3"  = ""
"*.flac" = ""
"*.wav"  = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""

# Images
"*.jpg"  = ""
"*.jpeg" = ""
"*.png"  = ""
"*.gif"  = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp"  = ""
"*.ico"  = ""
"*.svg"  = ""

# Programming
"*.c"     = ""
"*.cpp"   = ""
"*.h"     = ""
"*.hpp"   = ""
"*.rs"    = ""
"*.go"    = ""
"*.py"    = ""
"*.js"    = ""
"*.ts"    = ""
"*.tsx"   = ""
"*.jsx"   = ""
"*.rb"    = ""
"*.php"   = ""
"*.java"  = ""
"*.sh"    = ""
"*.fish"  = ""
"*.swift" = ""
"*.vim"   = ""
"*.lua"   = ""
"*.html"  = ""
"*.css"   = ""
"*.scss"  = ""
"*.json"  = ""
"*.toml"  = ""
"*.yml"   = ""
"*.yaml"  = ""
"*.ini"   = ""
"*.conf"  = ""

# Default
"*"  = ""
"*/" = ""

