[manager]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000

[opener]
folder = [
	{ exec = 'open -R "$@"', display_name = "Reveal in Finder" },
	{ exec = 'code "$@"' },
]
archive = [
	{ exec = 'unar "$1"', display_name = "Extract here" },
	{ exec = '/Applications/MacZip.app/Contents/MacOS/MacZip "$1"', orphan = true, display_name = "MacZip" },
]
text = [
	{ exec = 'nvim "$1"', block = true },
	{ exec = 'code "$@"' },
]
video = [
	{ exec = 'mpv "$@"' },
	{ exec = 'iina "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" }
]
audio = [
	{ exec = 'mpv "$@"' },
	{ exec = 'iina "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
