[opener]
archive = [
	{ cmd = "unar", args = [ "$1" ] },
	{ cmd = "/Applications/MacZip.app/Contents/MacOS/MacZip", args = [ "$1" ] },
]
text = [
	{ cmd = "nvim", args = [ "$*" ], block = true },
	{ cmd = "code", args = [ "$*" ] },
]
video = [
	{ cmd = "mpv", args = [ "$*" ] },
	{ cmd = "iina", args = [ "$*" ] },
	{ cmd = "mediainfo", args = [ "$1" ], block = true },
]
audio = [
	{ cmd = "mpv", args = [ "$*" ] },
	{ cmd = "iina", args = [ "$*" ] },
	{ cmd = "mediainfo", args = [ "$1" ], block = true },
]
