[opener]
folder = [
	{ cmd = "open", args = [ "-R", "$*" ] },
	{ cmd = "code", args = [ "$*" ] },
]
archive = [
	{ cmd = "unar", args = [ "$0" ] },
	{ cmd = "/Applications/MacZip.app/Contents/MacOS/MacZip", args = [ "$0" ] },
]
text = [
	{ cmd = "nvim", args = [ "$*" ], block = true },
	{ cmd = "code", args = [ "$*" ] },
]
video = [
	{ cmd = "mpv", args = [ "$*" ] },
	{ cmd = "iina", args = [ "$*" ] },
	{ cmd = "mediainfo", args = [ "$0" ], block = true },
]
audio = [
	{ cmd = "mpv", args = [ "$*" ] },
	{ cmd = "iina", args = [ "$*" ] },
	{ cmd = "mediainfo", args = [ "$0" ], block = true },
]
