[preview]
max_width  = 2160
max_height = 3840

[opener]
folder = [
	{ exec = 'open -R "$@"', display_name = "Reveal in Finder" },
	{ exec = 'code "$@"' },
]
archive = [
	{ exec = 'unar "$1"', display_name = "Extract here" },
	{ exec = '/Applications/MacZip.app/Contents/MacOS/MacZip "$1"', display_name = "MacZip" },
]
text = [
	{ exec = 'nvim "$1"', block = true },
	{ exec = 'code "$@"' },
]
video = [
	{ exec = 'mpv "$@"' },
	{ exec = 'iina "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" }
]
audio = [
	{ exec = 'mpv "$@"' },
	{ exec = 'iina "$@"' },
	{ exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, display_name = "Show media info" },
]
